config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  resources :posts do
    collection do
      post 'search'
      get 'search'
    end
    resources :incomes
  end
  devise_for :users

  root 'posts#index'

end

app/models/income.rb
class Income < ActiveRecord::Base
  belongs_to :post
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]
  before_filter :set_incomes!

  # GET /expensesbases
  # GET /expensesbases.json
  def index
    @incomes = @post.incomes.all
  end

  # GET /expensesbases/1
  # GET /expensesbases/1.json
  def show
  end

  # GET /expensesbases/new
  def new
    @expensesbasis = Expensesbase.new
  end

  # GET /expensesbases/1/edit
  def edit
  end

  # POST /expensesbases
  # POST /expensesbases.json
  def create
    @expensesbasis = @post.expensesbases.new(expensesbasis_params)

    respond_to do |format|
      if @expensesbasis.save
        format.html { redirect_to [@post, @expensesbasis], notice: 'Expensesbase was successfully created.' }
        format.json { render :show, status: :created, location: @expensesbasis }
      else
        format.html { render :new }
        format.json { render json: @expensesbasis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expensesbases/1
  # PATCH/PUT /expensesbases/1.json
  def update
    respond_to do |format|
      if @expensesbasis.update(expensesbasis_params)
        format.html { redirect_to [@post, @expensesbasis], notice: 'Expensesbase was successfully updated.' }
        format.json { render :show, status: :ok, location: @expensesbasis }
      else
        format.html { render :edit }
        format.json { render json: @expensesbasis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expensesbases/1
  # DELETE /expensesbases/1.json
  def destroy
    @expensesbasis.destroy
    respond_to do |format|
      format.html { redirect_to [@post, @expensesbasis], notice: 'Expensesbase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expensesbasis
      @expensesbasis = Expensesbase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expensesbasis_params
      params.require(:expensesbasis).permit(:date, :sum, :post_id)
    end

    def set_incomes!
      @post = Post.find(params[:post_id]) rescue nil
      if !@post
        redirect_to root_path, :alert => "Post not found!"
      end
    end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/_form.html.slim
= form_for [@post, @income] do |f|
  - if @income.errors.any?
    #error_explanation
      h2 = "#{pluralize(@income.errors.count, "error")} prohibited this income from being saved:"
      ul
        - @income.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :date
    = f.date_select :date
  .field
    = f.label :sum
    = f.number_field :sum
  .actions = f.submit

app/views/incomes/edit.html.slim
h1 Editing income

== render 'form'

= link_to 'Show', [@post, @income]
'|
= link_to 'Back', post_incomes_path(@post)

app/views/incomes/index.html.slim
h1 Listing incomes

table
  thead
    tr
      th Date &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
      th Sum &ensp;
      th Income
      th &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
      th &ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;
      th

  tbody
    - @incomes.each do |income|
      tr
        td = income.date
        td = income.sum
        td = link_to 'Show', [@post, income]
        td = link_to 'Edit', edit_post_income_path(@post, income) 
        td = link_to 'Destroy', post_income_path(@post, income), :method => :delete, :data => { :confirm => 'Are you sure?' }


br

= link_to 'New Income', new_post_income_path

app/views/incomes/new.html.slim
h1 New income

== render 'form'

= link_to 'Back', post_incomes_path(@post)

app/views/incomes/show.html.slim
p#notice = notice

p
  strong Date:
  = @income.date
p
  strong Sum:
  = @income.sum
p
  strong Income:

= link_to 'Edit', edit_post_income_path(@post, @income)
'|
= link_to 'Back', post_incomes_path(@post)