config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  resources :posts do
    collection do
      post 'search'
      get 'search'
    end
    resources :incomes
  end
  devise_for :users

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :incomes
  has_many :expenses

  def self.to_csv(options ={})
  	CSV.generate(options) do |csv|
  		csv << column_names
  		all.each do |post|
  			csv << post.attributes.values_at(*column_names)
  		end
  	end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where(user_id: current_user)
    @postses = @posts.where(created_at: '2016-07-03 12:18:18.979389'..'2016-07-05 22:42:19.202147')
    @post = Post.new
    respond_to do |format|
        format.html { }
        format.csv { send_data @date.to_csv }
        format.xls { send_data @posts.to_csv(col_sep: "\t") }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  def add_incomes
    @incomes = Income.all
  end

  def search
  #@d = params.require(:date).permit(:year, :month, :day)
  #@d = params[:date][:year].to_i
   #@m = Date.new(params[:event].values.map(&:to_i))
   #permitted = params.permit(start_date: [ :name, { pets: :name } ])
   s = Date.civil(params[:date][:year].to_i, params[:date][:month].to_i, params[:date][:day].to_i) rescue nil
   if s
    @d = s
   end
   #d = Date.civil(params[:date][:year].to_i, params[:date][:month].to_i, params[:date][:day].to_i)
   #if !d
    #@s=d
   #end
   #@m = d.to_s
   #params.require(:person).permit(:name, :age)
   #@date = Date.new(post_params)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.slim
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .actions = f.submit

app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

= link_to 'Show', @post
'|
= link_to 'Back', posts_path

app/views/posts/index.html.slim
h2 Expense

p Download:
= link_to 'CSV', posts_path(format: "csv"), class: 'btn btn-default'
= link_to 'XLS', posts_path(format: "xls"), class: 'btn btn-default'

- @posts.each do |post|
  h1 = link_to post.title, post_incomes_path(post)
  p = post.content
  s = post.user_id

  div
    b Author: 
    = post.user.email

= link_to 'New expense', new_post_path, class: 'btn btn-default'
= link_to 'Search', search_posts_path, class: 'btn btn-default'

h1 New post

== render 'form'

app/views/posts/new.html.slim
h1 New post

== render 'form'

= link_to 'Back', posts_path

app/views/posts/search.html.slim
= form_tag '/posts/search', :method => :post do
 .field
  = select_date Date.today
  .actions = submit_tag("Search")

  p
  strong User:
  = @d

app/views/posts/show.html.slim
d#notice = notice

p
  strong Date:
  strong Sum:
p
  <input type="text" data-provide='datepicker' >
   <input type="text">
p
  strong User:
  = @post.id


= link_to 'Edit', edit_post_path(@post)
'|
= link_to 'Back', posts_path