config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  resources :posts do
    collection do
      post 'search'
      get 'search'
    end
    resources :incomes
  end
  devise_for :users

  root 'posts#index'

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expensesbasis, only: [:show, :edit, :update, :destroy]
  before_filter :set_expenses!

  # GET /expensesbases
  # GET /expensesbases.json
  def index
    @expensesbases = @post.expensesbasis.all
  end

  # GET /expensesbases/1
  # GET /expensesbases/1.json
  def show
  end

  # GET /expensesbases/new
  def new
    @expensesbasis = Expensesbase.new
  end

  # GET /expensesbases/1/edit
  def edit
  end

  # POST /expensesbases
  # POST /expensesbases.json
  def create
    @expensesbasis = @post.expensesbases.new(expensesbasis_params)

    respond_to do |format|
      if @expensesbasis.save
        format.html { redirect_to [@post, @expensesbasis], notice: 'Expensesbase was successfully created.' }
        format.json { render :show, status: :created, location: @expensesbasis }
      else
        format.html { render :new }
        format.json { render json: @expensesbasis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expensesbases/1
  # PATCH/PUT /expensesbases/1.json
  def update
    respond_to do |format|
      if @expensesbasis.update(expensesbasis_params)
        format.html { redirect_to [@post, @expensesbasis], notice: 'Expensesbase was successfully updated.' }
        format.json { render :show, status: :ok, location: @expensesbasis }
      else
        format.html { render :edit }
        format.json { render json: @expensesbasis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expensesbases/1
  # DELETE /expensesbases/1.json
  def destroy
    @expensesbasis.destroy
    respond_to do |format|
      format.html { redirect_to [@post, @expensesbasis], notice: 'Expensesbase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expensesbasis
      @expensesbasis = Expensesbase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expensesbasis_params
      params.require(:expensesbasis).permit(:date, :sum, :post_id)
    end

    def set_expenses!
      @post = Post.find(params[:post_id]) rescue nil
      if !@post
        redirect_to root_path, :alert => "Post not found!"
      end
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.slim
= form_for @expense do |f|
  - if @expense.errors.any?
    #error_explanation
      h2 = "#{pluralize(@expense.errors.count, "error")} prohibited this expense from being saved:"
      ul
        - @expense.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :date
    = f.date_select :date
  .field
    = f.label :sum
    = f.number_field :sum
  .field
    = f.label :expense_id
    = f.number_field :expense_id
  .actions = f.submit

app/views/expenses/edit.html.slim
h1 Editing expense

== render 'form'

= link_to 'Show', @expense
'|
= link_to 'Back', expenses_path

app/views/expenses/index.html.slim
h1 Listing expenses

table
  thead
    tr
      th Date
      th Sum
      th Expense
      th
      th
      th

  tbody
    - @expenses.each do |expense|
      tr
        td = expense.date
        td = expense.sum
        td = expense.expense_id
        td = link_to 'Show', expense
        td = link_to 'Edit', edit_expense_path(expense)
        td = link_to 'Destroy', expense, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Expense', new_expense_path

app/views/expenses/new.html.slim
h1 New expense

== render 'form'

= link_to 'Back', expenses_path

app/views/expenses/show.html.slim
p#notice = notice

p
  strong Date:
  = @expense.date
p
  strong Sum:
  = @expense.sum
p
  strong Expense:
  = @expense.expense_id

= link_to 'Edit', edit_expense_path(@expense)
'|
= link_to 'Back', expenses_path